'''
Created on Mar 10, 2016

@author: Richard
'''
from constants import BROWN, GREEN, BLUE, RED, CYAN, MAGENTA, YELLOW
COLOURED_TILE_MARGIN = 0.01
IPIECE_COLOUR = BROWN
JPIECE_COLOUR = GREEN
LPIECE_COLOUR = BLUE
OPIECE_COLOUR = RED
SPIECE_COLOUR = CYAN
TPIECE_COLOUR = MAGENTA
ZPIECE_COLOUR = YELLOW